flask_application/forms.py
from flask.ext.wtf import Form, TextField, PasswordField, DateField, IntegerField, SelectField
from flask.ext.wtf import Required, Email, EqualTo, Length, validators, URL, Optional

class RegisterForm(Form):
    name = TextField('Username', validators=[Required(), Length(min=3, max=25)])
    email = TextField('Email', validators=[Required(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[Required(), Length(min=6, max=40)])
    confirm = PasswordField(
                'Repeat Password',
                [Required(), EqualTo('password', message='Passwords must match')])

class LoginForm(Form):
    name = TextField('Username', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])

class PostLink(Form):
    #link = TextField('Link',[
                                        #validators.EqualTo(URL(require_tld = True), message='Invalid URL!')
                                        #Length(min=3, max=60))
                                        #])
    #link = TextField('Link', validators=[Optional(), URL(require_tld=False)])
    link = TextField('Group', validators = [Required(), Length(min=1, max=60)])
    group = TextField('Group', validators = [Required(), Length(min=3, max=50)])

class PostGroup(Form):
    group = TextField('Group', validators = [Required(), Length(min=1, max=50)])

flask_application/__init__.py
import os


FLASK_APP_DIR = os.path.dirname(os.path.abspath(__file__))

# Flask
from flask import Flask


app = Flask(__name__)


# Config
if True: #os.getenv('DEV') == 'yes':
    app.config.from_object('flask_application.config.ProductionConfig')
    app.logger.info("Config: Development")
elif os.getenv('TEST') == 'yes':
    app.config.from_object('flask_application.config.TestConfig')
    app.logger.info("Config: Test")
else:
    app.config.from_object('flask_application.config.ProductionConfig')
    app.logger.info("Config: Production")

# Logging
import logging
logging.basicConfig(
    level=logging.DEBUG,
    format='[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s',
    datefmt='%Y%m%d-%H:%M%p',
)

# Email on errors
if not app.debug and not app.testing:
    import logging.handlers
    mail_handler = logging.handlers.SMTPHandler(
                        'localhost',
                        os.getenv('USER'),
                        app.config['SYS_ADMINS'],
                        '{0} error'.format(app.config['SITE_NAME'],
                        ),
                    )
    mail_handler.setFormatter(logging.Formatter('''
Message type:       %(levelname)s
Location:           %(pathname)s:%(lineno)d
Module:             %(module)s
Function:           %(funcName)s
Time:               %(asctime)s

Message:

%(message)s
    '''.strip()))
    mail_handler.setLevel(logging.ERROR)
    app.logger.addHandler(mail_handler)
    app.logger.info("Emailing on error is ENABLED")
else:
    app.logger.info("Emailing on error is DISABLED")

# Assets
from flask.ext.assets import Environment
assets = Environment(app)
# Ensure output directory exists
assets_output_dir = os.path.join(FLASK_APP_DIR, 'static', 'gen')
if not os.path.exists(assets_output_dir):
    os.mkdir(assets_output_dir)

# Email
from flask.ext.mail import Mail, Message
mail = Mail(app)

# Memcache
from werkzeug.contrib.cache import MemcachedCache
app.cache = MemcachedCache(app.config['MEMCACHED_SERVERS'])
def cache_fetch(key, value_function, timeout=None):
    '''Mimicking Rails.cache.fetch'''
    global app
    self = app.cache
    data = self.get(key)
    if data is None:
        data = value_function()
        self.set(key, data, timeout)
    return data
app.cache.fetch = cache_fetch

# Helpers
from flask_application.helpers import datetimeformat
app.jinja_env.filters['datetimeformat'] = datetimeformat

# Business Logic
# http://flask.pocoo.org/docs/patterns/packages/
# http://flask.pocoo.org/docs/blueprints/
from flask_application.controllers.frontend import frontend
app.register_blueprint(frontend)



from flask.ext.security import Security, SQLAlchemyUserDatastore, \
    UserMixin, RoleMixin, login_required
from flask_application.models import db, User, Role
from flask_application.security_extras import ExtendedRegisterForm

# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore, register_form=ExtendedRegisterForm)

flask_application/controllers/__init__.py
# http://flask.pocoo.org/docs/patterns/packages/

flask_application/controllers/admin.py
from flask import Blueprint, render_template
from flask.ext.security import (login_required, roles_required, roles_accepted)
from flask_application.models import *

admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route('/admin')
@roles_required('admin')
def admin_page():
    return render_template('security/index.html', content='Admin Page')

@admin.route('/admin_or_editor')
@roles_accepted('admin', 'editor')
def admin_or_editor():
    return render_template('security/index.html', content='Admin or Editor Page')

flask_application/controllers/frontend.py
#!/usr/bin/env python

import datetime

from flask import Blueprint, render_template, flash, redirect, request, session, url_for, jsonify
from urlparse import urlparse
from flask_application import app
from flask.ext.security import *
import stripe

# -- ported --#
from functools import wraps
from flask_application.forms import RegisterForm, LoginForm, PostLink, PostGroup
from flask_application.models import *
from sqlalchemy.exc import *
from flask_application.xgoogle.search import GoogleSearch, SearchError

#from config import stripe_keys
#from flask_application.config import DEFAULT_SMALL_AMOUNT, DEFAULT_SMALL_DESCRIPTION, DEFAULT_LARGE_AMOUNT, DEFAULT_LARGE_DESCRIPTION

stripe.api_key = app.config['SECRET_KEY']

frontend = Blueprint('frontend', __name__)


@frontend.route('/')
def index():
    return render_template(
                'index.html',
                config=app.config,
                now=datetime.datetime.now,
            )
@app.route('/pricing' ,methods=['GET'])
def pricing():
    """handles our message notification"""
    return render_template('pricing.html')

@frontend.route('/profile')
@login_required
def profile():
    return render_template(
        'profiles/profile.html',
        content='Profile Page')

#-- Handle Payments with Stripe--#

"""
@app.route('/charge', methods=['POST'])
def charge():

  customer_email = request.form['email']



  customer = stripe.Customer.create(
          email=customer_email,
          card=request.form['stripeToken']
          )

  customer_id = customer.id

    # save the customer ID in DB for later use
  save_stripe_customer(customer_email, customer_id)

  # charge the customer (new or already present in DB)
  charge_valid, charge_msg = stripe_charge(customer_id)

  return render_template('charge.html',
          amount_usd=get_amount_usd(),
          customer_email=customer_email,
          charge_valid=charge_valid,
          charge_msg=charge_msg)
"""


"""@frontend.route('/small', methods=['GET', 'POST'])
def small():
        return render_template('small.html',
          key = app.config['PUBLISHABLE_KEY'],
          amount_usd=get_amount_usd()
          )
def get_amount_usd(amount=525):
    return float(amount) / 100

def get_stripe_customer(customer_email):


  customer_info = User.query.filter_by(email=customer_email).all

  if(customer_info == None):
    return False, customer_info
  else:
    return True, customer_info

def save_stripe_customer(customer_email, customer_id):

  # If already have a customer by that email, delete old entry
  reply, entry = get_stripe_customer(customer_email)
  if(reply):
    return "your already have an account with us! Log in to upgrade."
  else:
    if form.validate_on_submit():
      new_user = User(
                         form.group.data,
                         uid,
                         )
              db.session.flush()
              db.session.add(new_user)
              db.session.commit()
              flash("!")
"""


#-- ported from og template -- #

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,error), 'error')


@frontend.route('/')
def home():
  return render_template('home.html')


"""@frontend.route('/registertest/', methods=['GET', 'POST'])

def registertest():
    Registers the user.
    error=None
    if request.method == 'POST':
        if not request.form['username']:
            error = 'You have to enter a username'
        elif not request.form['email'] or \
                 '@' not in request.form['email']:
            error = 'You have to enter a valid email address'
        elif not request.form['password']:
            error = 'You have to enter a password'
        elif request.form['password'] != request.form['password2']:
            error = 'The two passwords do not match'
        elif request.form['username'] is not None:
            error = 'The username is already taken'
        else:
           if form.validate_on_submit():
            pw_hash=generate_password_hash(request.form['password'])
            username=request.form['username']
            email=request.form['email']
            level=0
            new_user = User(
                         username,
                         email,
                         uid,
                         )
            db.session.flush()
            db.session.add(new_group)
            db.session.commit()

            flash('You were successfully registered and can login now')
            return redirect(url_for('login'))
    return render_template('registertest.html', error=error)"""

# Generate Google search Query URL for demo
@frontend.route('/demo/', methods=['GET', 'POST'])
def generateurldemo():
  error=None
  uid = User.query.get(32)

  form = PostLink(request.form, csrf_enabled = False)
  groups = Groups.query.filter_by(user_id=uid.id).all()


  if request.method=='POST':
    flash("You created a custom google search!")
    group_passed = request.form['grp']
    search_passed = request.form['srch']
    links = Links.query.filter_by(author_id=uid.id,group_id=group_passed)
    out_str = ' '
    for link in links:
      out_str += 'site%3A'+link.link+'+OR+'
     #grab final
    final = 'https://www.google.com/search?q='+search_passed+out_str
    #Use this for API
    #return redirect(final, 301)
    return render_template('demo.html', form=form, groups=groups, group_passed=group_passed, search_passed=search_passed, links=links, out_str=out_str, final=final)

  else:
    goog_url = 'GET'
    return render_template('demo.html', goog_url = goog_url, form=form, groups=groups)

@frontend.route('/groups/', methods=['GET','POST'])
@login_required
def members():
    error=None
    form = PostGroup(request.form, csrf_enabled = False)
    uid = session['user_id']
    groups = Groups.query.filter_by(user_id=uid).all()

    for group in groups:
      if request.method=='POST':
          if form.validate_on_submit():
            if form.group.data == group.name:
              flash('That group already exists!')
              return render_template('members.html', form=form, error=error, groups=groups)
            else:
              new_group = Groups(
                         form.group.data,
                         uid,
                         )
              db.session.flush()
              db.session.add(new_group)
              db.session.commit()
              flash("You created a group, time to add some links!")
              return redirect(url_for('.members'))
          else:
              flash("That group didn't work, maybe the name is too long?")
              return redirect(url_for('.members'))
              #flash_errors(form)

    if request.method=='POST':
          if form.validate_on_submit():
              new_group = Groups(
                         form.group.data,
                         uid,
                         )
              db.session.flush()
              db.session.add(new_group)
              db.session.commit()
              # db.session.flush()
              flash("You have created your first group!")
              return redirect(url_for('.members'))
          else:
              flash_errors(form)
    return render_template('members.html', form=form, error=error, groups=groups)

@frontend.route('/groups/<group>', methods=['GET','POST'])
@login_required
def memberextend(group):
    error=None
    form = PostLink(request.form, csrf_enabled = False)
    uid = session['user_id']
    groups = Groups.query.filter_by(user_id=uid)
    links = Links.query.filter_by(author_id=uid,group_id=group)

    for link in links:
      #return group
      if request.method=='POST':
          if form.validate_on_submit():
             if form.link.data == link.link:
                flash('That link already exists!')
                return render_template('add_link.html', form=form, error=error, tester = group, uid=uid, groups=groups, links=links)
             else:
              new_link = Links(
                         uid,
                         form.link.data,
                         group,
                         )
             db.session.add(new_link)
             db.session.commit()

             flash("You have added a link!")
             return redirect('/groups/'+group)
          else:
           flash_errors(form)
    if request.method=='POST':
      if form.validate_on_submit():
            new_link = Links(
                       uid,
                       form.link.data,
                       group,
                     )
            db.session.add(new_link)
            db.session.commit()
            flash("You have added your first link!")
            return redirect('/groups/'+group)
      else:
           flash_errors(form)
    return render_template('add_link.html', form=form, error=error, tester = group, uid=uid, groups=groups, links=links)

#Delete group functionality
@frontend.route('/<group_to_delete>/deletegroup/', methods=['POST'])
@login_required
def deletegroup(group_to_delete):
    error=None
    uid = session['user_id']
    groups = Groups.query.filter_by(user_id=uid, name =group_to_delete)
    links = Links.query.filter_by(author_id=uid,group_id=group_to_delete)
    for group in groups:
      db.session.delete(group)
      for link in links:
        db.session.delete(link)
    db.session.commit()
    return redirect(url_for('.members'))

#Delete link functionality
@frontend.route('/<link_to_delete>/deletelink/', methods=['POST'])
@login_required
def deletelink(link_to_delete):

    error=None
    uid = session['user_id']
    links = Links.query.filter_by(author_id=uid,link=link_to_delete)
    for link in links:
      #return group.name
      db.session.delete(link)

      db.session.commit()
      return redirect(url_for('.members', group=link_to_delete))

# Generate Google search Query URL

flask_application/xgoogle/__init__.py
#!/usr/bin/python
#
# Peteris Krumins (peter@catonmat.net)
# http://www.catonmat.net  --  good coders code, great reuse
#
# A Google Python library:
# http://www.catonmat.net/blog/python-library-for-google-search/
#
# Distributed under MIT license:
#
# Copyright (c) 2009 Peteris Krumins
#
# Permission is hereby granted, free of charge, to any person
# Obtaining a copy of this software and associated documentation
# Files (the "Software"), to deal in the Software without
# Restriction, including without limitation the rights to use,
# Copy, modify, merge, publish, distribute, sublicense, and/or sell
# Copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# Conditions:
#
# The above copyright notice and this permission notice shall be
# Included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

flask_application/templates/bootstrap/layouts/base.html
<!DOCTYPE html>
<html lang="{% block html_lang %}en{% endblock %}">
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"></script>
    <script src="http://w3resource.com/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-tooltip.js"></script>
      <script src="http://w3resource.com/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-popover.js"></script>
   <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Cabin" rel="stylesheet" type="text/css">
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_ilOGiFHlu0cP4oPxB2Jui5EH');

var stripeResponseHandler = function(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and re-submit
        $form.get(0).submit();
      }
    };

    jQuery(function($) {
      $('#payment-form').submit(function(e) {
        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('button').prop('disabled', true);

        Stripe.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
      });
    });
  </script>

</script>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

{% from "bootstrap/macros.html" import debugmin %}
{% block head %}
    <title>{% block title %}{% endblock %} | {{ config['SITE_NAME'] }}</title>
    {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        <meta name="author" content="{% block meta_author %}{% endblock %}">
    {% endblock %}

    {% block css_bootstrap %}



    {% assets filters="cssmin", output="gen/packed.css", "css/bootstrap.css", "css/bootstrap-responsive.css"%}
          <link rel="stylesheet" href="{{ ASSET_URL }}"/>
    {% endassets %}
    {% endblock %}

    {% block css_site %}
    {% endblock %}
    {% block css_extra %}
    {% endblock %}

    {% block js_html5_shim %}
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    {% endblock %}
{% endblock %}


    <style> body {
        padding-top: 0px;
        padding-bottom: 40px;
    }
    /* Custom container */
    .container-narrow {
        margin: 0 auto;
        max-width: 750px;

    }
    .container-narrow > hr {
        margin: 30px 0;
    }
   /* Custom container */
    .container-main {
        padding-top: 50px;
        padding-left: 30px;
        padding-bottom: 30px;
        margin: 70 auto;
        margin-top: 100px;
        max-width: 800px;
        background-color: #fff;

    }
    .container-main > hr {
        margin: 120px 0;
    }

    .flash          { background: #fff; padding: 0.5em; }
    .error          { background: #fff; padding: 0.5em; }

.subtitles {
  display: block;
  text-align: center;

  width: 100%;
  padding: 0;
  margin-bottom: 20px;

  font-size: 21px;
  line-height: 40px;
  color:#FFFFFF;
   font-family: 'Cabin', Helvetica, Arial, sans-serif;



}

  </style>


<script type = "text/javascript">
function do_change(){
  var list = document.getElementsByClassName("confirm");
  for (var i = 0; i < list.length; i++)  {
      list[i].style.display="inline";

  }
}

</script>
</head>


<body class="{% block body_classes %}{% endblock %}" id="{% block body_id %}{% endblock %}"{% block bodytag_extra %}{% endblock %}>
{% block body %}

    {% block navbar_wrapper %}

    {% endblock %}

    {% block pre_container %}

    {% endblock %}


    {% block container_wrapper %}
        <div class="container ">

            {% block container %}

                {% block messages %}
                    {% include "bootstrap/includes/messages.html" %}
                {% endblock %}

                {% block pre_content %}
                {% endblock %}

                {% block content %}
                {% endblock %}


                {% block post_content %}
                {% endblock %}

            {% endblock %}
        </div>
    {% endblock %}


    {% block post_container %}
    {% endblock %}

    {% block js_jquery %}
        {# Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline #}
        {#<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{{ url_for('static', filename='js/jquery-1.7.1.min.js') }}"><\/script>')</script>#}
    {% endblock %}

    {% block js_bootstrap %}
        <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap-dropdown.js') }}"></script>
    {% endblock %}

<div class="modal-footer">
  <p style="color:white">
<a href ="{{ url_for('frontend.index') }}">Home</a>
<b>·</b>

<a href ="/auth/register">Sign Up</a>
<b>·</b>

<a href ="mailto:info@thesearchcollective.net">Email Us</a>
</p>
</div>
    {% block js_footer %}
           {#<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"></script>#}
           <script type="text/javascript">
$(document).ready(function(){
    $('.formy').click(function(){
        var answer = confirm("Are you sure you want to delete this link?");
        if (answer){
            return true;
        } else {
            return false;
        }
    });
});
</script>
<script type="text/javascript">
$(document).ready(function(){
    $('.groupconfirm').click(function(){
        var answer = confirm("Are you sure you want to delete the entire group?");
        if (answer){
            return true;
        } else {
            return false;
        }
    });
});
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43812908-1', 'thesearchcollective.net');
  ga('send', 'pageview');

</script>

<script>
      $(function (){
         $("#example").popover();
      });
      </script>

    {% endblock %}

{% endblock %}
</body>
</html>

flask_application/templates/bootstrap/layouts/base_navbar_responsive.html
{% extends "bootstrap/layouts/base.html" %}

{% block css_bootstrap %}
    {{ super() }}
    {# TODO: probably remove this and let the user set it manually? #}
    <style>
        body {
            padding-top: 0px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
{% endblock %}

{% block navbar_wrapper %}
<div class="container">
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            {% block navbar_container %}
                {#<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>#}
               {% block navbar_links %}
               <style>
                .banner {
                        font-family: 'Lobster', Georgia, Times, serif;
                        font-size: 35px;
                        line-height: 20px;
                        text-decoration: none;

                    }
               </style>
                    <a  class="banner" href="/">{{ config['SITE_NAME'] }}</a>
                    {#<a href="/"><img src="/static/img/tsclogo2.png" alt="the search collective"></a>#}
                    {#<a class="brand" href="/">{{ config['SITE_NAME'] }}</a>#}
                    {# <div class="nav-collapse">
                        <ul class="nav">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>#}
                {% endblock %}
                {% include "security/_menu.html" %}

            {% endblock %}
        </div>
    </div>
</div>

</div>

{% endblock %}