flask_application/forms.py
from flask.ext.wtf import Form, TextField, PasswordField, DateField, IntegerField, SelectField
from flask.ext.wtf import Required, Email, EqualTo, Length, validators, URL, Optional

class RegisterForm(Form):
    name = TextField('Username', validators=[Required(), Length(min=3, max=25)])
    email = TextField('Email', validators=[Required(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[Required(), Length(min=6, max=40)])
    confirm = PasswordField(
                'Repeat Password',
                [Required(), EqualTo('password', message='Passwords must match')])

class LoginForm(Form):
    name = TextField('Username', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])

class PostLink(Form):
    #link = TextField('Link',[
                                        #validators.EqualTo(URL(require_tld = True), message='Invalid URL!')
                                        #Length(min=3, max=60))
                                        #])
    #link = TextField('Link', validators=[Optional(), URL(require_tld=False)])
    link = TextField('Group', validators = [Required(), Length(min=1, max=60)])
    group = TextField('Group', validators = [Required(), Length(min=3, max=50)])

class PostGroup(Form):
    group = TextField('Group', validators = [Required(), Length(min=1, max=50)])

flask_application/__init__.py
import os


FLASK_APP_DIR = os.path.dirname(os.path.abspath(__file__))

# Flask
from flask import Flask


app = Flask(__name__)


# Config
if True: #os.getenv('DEV') == 'yes':
    app.config.from_object('flask_application.config.ProductionConfig')
    app.logger.info("Config: Development")
elif os.getenv('TEST') == 'yes':
    app.config.from_object('flask_application.config.TestConfig')
    app.logger.info("Config: Test")
else:
    app.config.from_object('flask_application.config.ProductionConfig')
    app.logger.info("Config: Production")

# Logging
import logging
logging.basicConfig(
    level=logging.DEBUG,
    format='[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s',
    datefmt='%Y%m%d-%H:%M%p',
)

# Email on errors
if not app.debug and not app.testing:
    import logging.handlers
    mail_handler = logging.handlers.SMTPHandler(
                        'localhost',
                        os.getenv('USER'),
                        app.config['SYS_ADMINS'],
                        '{0} error'.format(app.config['SITE_NAME'],
                        ),
                    )
    mail_handler.setFormatter(logging.Formatter('''
Message type:       %(levelname)s
Location:           %(pathname)s:%(lineno)d
Module:             %(module)s
Function:           %(funcName)s
Time:               %(asctime)s

Message:

%(message)s
    '''.strip()))
    mail_handler.setLevel(logging.ERROR)
    app.logger.addHandler(mail_handler)
    app.logger.info("Emailing on error is ENABLED")
else:
    app.logger.info("Emailing on error is DISABLED")

# Assets
from flask.ext.assets import Environment
assets = Environment(app)
# Ensure output directory exists
assets_output_dir = os.path.join(FLASK_APP_DIR, 'static', 'gen')
if not os.path.exists(assets_output_dir):
    os.mkdir(assets_output_dir)

# Email
from flask.ext.mail import Mail, Message
mail = Mail(app)

# Memcache
from werkzeug.contrib.cache import MemcachedCache
app.cache = MemcachedCache(app.config['MEMCACHED_SERVERS'])
def cache_fetch(key, value_function, timeout=None):
    '''Mimicking Rails.cache.fetch'''
    global app
    self = app.cache
    data = self.get(key)
    if data is None:
        data = value_function()
        self.set(key, data, timeout)
    return data
app.cache.fetch = cache_fetch

# Helpers
from flask_application.helpers import datetimeformat
app.jinja_env.filters['datetimeformat'] = datetimeformat

# Business Logic
# http://flask.pocoo.org/docs/patterns/packages/
# http://flask.pocoo.org/docs/blueprints/
from flask_application.controllers.frontend import frontend
app.register_blueprint(frontend)



from flask.ext.security import Security, SQLAlchemyUserDatastore, \
    UserMixin, RoleMixin, login_required
from flask_application.models import db, User, Role
from flask_application.security_extras import ExtendedRegisterForm

# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore, register_form=ExtendedRegisterForm)

flask_application/controllers/__init__.py
# http://flask.pocoo.org/docs/patterns/packages/

flask_application/controllers/admin.py
from flask import Blueprint, render_template
from flask.ext.security import (login_required, roles_required, roles_accepted)
from flask_application.models import *

admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route('/admin')
@roles_required('admin')
def admin_page():
    return render_template('security/index.html', content='Admin Page')

@admin.route('/admin_or_editor')
@roles_accepted('admin', 'editor')
def admin_or_editor():
    return render_template('security/index.html', content='Admin or Editor Page')

flask_application/controllers/frontend.py
#!/usr/bin/env python

import datetime

from flask import Blueprint, render_template, flash, redirect, request, session, url_for, jsonify
from urlparse import urlparse
from flask_application import app
from flask.ext.security import *
import stripe

# -- ported --#
from functools import wraps
from flask_application.forms import RegisterForm, LoginForm, PostLink, PostGroup
from flask_application.models import *
from sqlalchemy.exc import *
from flask_application.xgoogle.search import GoogleSearch, SearchError

#from config import stripe_keys
#from flask_application.config import DEFAULT_SMALL_AMOUNT, DEFAULT_SMALL_DESCRIPTION, DEFAULT_LARGE_AMOUNT, DEFAULT_LARGE_DESCRIPTION

stripe.api_key = app.config['SECRET_KEY']

frontend = Blueprint('frontend', __name__)


@frontend.route('/')
def index():
    return render_template(
                'index.html',
                config=app.config,
                now=datetime.datetime.now,
            )
@app.route('/pricing' ,methods=['GET'])
def pricing():
    """handles our message notification"""
    return render_template('pricing.html')

@frontend.route('/profile')
@login_required
def profile():
    return render_template(
        'profiles/profile.html',
        content='Profile Page')

#-- Handle Payments with Stripe--#

"""
@app.route('/charge', methods=['POST'])
def charge():

  customer_email = request.form['email']



  customer = stripe.Customer.create(
          email=customer_email,
          card=request.form['stripeToken']
          )

  customer_id = customer.id

    # save the customer ID in DB for later use
  save_stripe_customer(customer_email, customer_id)

  # charge the customer (new or already present in DB)
  charge_valid, charge_msg = stripe_charge(customer_id)

  return render_template('charge.html',
          amount_usd=get_amount_usd(),
          customer_email=customer_email,
          charge_valid=charge_valid,
          charge_msg=charge_msg)
"""


"""@frontend.route('/small', methods=['GET', 'POST'])
def small():
        return render_template('small.html',
          key = app.config['PUBLISHABLE_KEY'],
          amount_usd=get_amount_usd()
          )
def get_amount_usd(amount=525):
    return float(amount) / 100

def get_stripe_customer(customer_email):


  customer_info = User.query.filter_by(email=customer_email).all

  if(customer_info == None):
    return False, customer_info
  else:
    return True, customer_info

def save_stripe_customer(customer_email, customer_id):

  # If already have a customer by that email, delete old entry
  reply, entry = get_stripe_customer(customer_email)
  if(reply):
    return "your already have an account with us! Log in to upgrade."
  else:
    if form.validate_on_submit():
      new_user = User(
                         form.group.data,
                         uid,
                         )
              db.session.flush()
              db.session.add(new_user)
              db.session.commit()
              flash("!")
"""


#-- ported from og template -- #

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,error), 'error')


@frontend.route('/')
def home():
  return render_template('home.html')


"""@frontend.route('/registertest/', methods=['GET', 'POST'])

def registertest():
    Registers the user.
    error=None
    if request.method == 'POST':
        if not request.form['username']:
            error = 'You have to enter a username'
        elif not request.form['email'] or \
                 '@' not in request.form['email']:
            error = 'You have to enter a valid email address'
        elif not request.form['password']:
            error = 'You have to enter a password'
        elif request.form['password'] != request.form['password2']:
            error = 'The two passwords do not match'
        elif request.form['username'] is not None:
            error = 'The username is already taken'
        else:
           if form.validate_on_submit():
            pw_hash=generate_password_hash(request.form['password'])
            username=request.form['username']
            email=request.form['email']
            level=0
            new_user = User(
                         username,
                         email,
                         uid,
                         )
            db.session.flush()
            db.session.add(new_group)
            db.session.commit()

            flash('You were successfully registered and can login now')
            return redirect(url_for('login'))
    return render_template('registertest.html', error=error)"""

# Generate Google search Query URL for demo
@frontend.route('/demo/', methods=['GET', 'POST'])
def generateurldemo():
  error=None
  uid = User.query.get(32)

  form = PostLink(request.form, csrf_enabled = False)
  groups = Groups.query.filter_by(user_id=uid.id).all()


  if request.method=='POST':
    flash("You created a custom google search!")
    group_passed = request.form['grp']
    search_passed = request.form['srch']
    links = Links.query.filter_by(author_id=uid.id,group_id=group_passed)
    out_str = ' '
    for link in links:
      out_str += 'site%3A'+link.link+'+OR+'
     #grab final
    final = 'https://www.google.com/search?q='+search_passed+out_str
    #Use this for API
    #return redirect(final, 301)
    return render_template('demo.html', form=form, groups=groups, group_passed=group_passed, search_passed=search_passed, links=links, out_str=out_str, final=final)

  else:
    goog_url = 'GET'
    return render_template('demo.html', goog_url = goog_url, form=form, groups=groups)

@frontend.route('/groups/', methods=['GET','POST'])
@login_required
def members():
    error=None
    form = PostGroup(request.form, csrf_enabled = False)
    uid = session['user_id']
    groups = Groups.query.filter_by(user_id=uid).all()

    for group in groups:
      if request.method=='POST':
          if form.validate_on_submit():
            if form.group.data == group.name:
              flash('That group already exists!')
              return render_template('members.html', form=form, error=error, groups=groups)
            else:
              new_group = Groups(
                         form.group.data,
                         uid,
                         )
              db.session.flush()
              db.session.add(new_group)
              db.session.commit()
              flash("You created a group, time to add some links!")
              return redirect(url_for('.members'))
          else:
              flash("That group didn't work, maybe the name is too long?")
              return redirect(url_for('.members'))
              #flash_errors(form)

    if request.method=='POST':
          if form.validate_on_submit():
              new_group = Groups(
                         form.group.data,
                         uid,
                         )
              db.session.flush()
              db.session.add(new_group)
              db.session.commit()
              # db.session.flush()
              flash("You have created your first group!")
              return redirect(url_for('.members'))
          else:
              flash_errors(form)
    return render_template('members.html', form=form, error=error, groups=groups)

@frontend.route('/groups/<group>', methods=['GET','POST'])
@login_required
def memberextend(group):
    error=None
    form = PostLink(request.form, csrf_enabled = False)
    uid = session['user_id']
    groups = Groups.query.filter_by(user_id=uid)
    links = Links.query.filter_by(author_id=uid,group_id=group)

    for link in links:
      #return group
      if request.method=='POST':
          if form.validate_on_submit():
             if form.link.data == link.link:
                flash('That link already exists!')
                return render_template('add_link.html', form=form, error=error, tester = group, uid=uid, groups=groups, links=links)
             else:
              new_link = Links(
                         uid,
                         form.link.data,
                         group,
                         )
             db.session.add(new_link)
             db.session.commit()

             flash("You have added a link!")
             return redirect('/groups/'+group)
          else:
           flash_errors(form)
    if request.method=='POST':
      if form.validate_on_submit():
            new_link = Links(
                       uid,
                       form.link.data,
                       group,
                     )
            db.session.add(new_link)
            db.session.commit()
            flash("You have added your first link!")
            return redirect('/groups/'+group)
      else:
           flash_errors(form)
    return render_template('add_link.html', form=form, error=error, tester = group, uid=uid, groups=groups, links=links)

#Delete group functionality
@frontend.route('/<group_to_delete>/deletegroup/', methods=['POST'])
@login_required
def deletegroup(group_to_delete):
    error=None
    uid = session['user_id']
    groups = Groups.query.filter_by(user_id=uid, name =group_to_delete)
    links = Links.query.filter_by(author_id=uid,group_id=group_to_delete)
    for group in groups:
      db.session.delete(group)
      for link in links:
        db.session.delete(link)
    db.session.commit()
    return redirect(url_for('.members'))

#Delete link functionality
@frontend.route('/<link_to_delete>/deletelink/', methods=['POST'])
@login_required
def deletelink(link_to_delete):

    error=None
    uid = session['user_id']
    links = Links.query.filter_by(author_id=uid,link=link_to_delete)
    for link in links:
      #return group.name
      db.session.delete(link)

      db.session.commit()
      return redirect(url_for('.members', group=link_to_delete))

# Generate Google search Query URL

flask_application/xgoogle/__init__.py
#!/usr/bin/python
#
# Peteris Krumins (peter@catonmat.net)
# http://www.catonmat.net  --  good coders code, great reuse
#
# A Google Python library:
# http://www.catonmat.net/blog/python-library-for-google-search/
#
# Distributed under MIT license:
#
# Copyright (c) 2009 Peteris Krumins
#
# Permission is hereby granted, free of charge, to any person
# Obtaining a copy of this software and associated documentation
# Files (the "Software"), to deal in the Software without
# Restriction, including without limitation the rights to use,
# Copy, modify, merge, publish, distribute, sublicense, and/or sell
# Copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# Conditions:
#
# The above copyright notice and this permission notice shall be
# Included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

flask_application/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  <p>
    {{ field.label }} {{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </p>
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

flask_application/templates/security/_menu.html
<ul class="nav nav-pills pull-right">


  {% if current_user.has_role('admin') -%}
  <li><a href="{{ url_for('admin.admin_page') }}">Admin</a></li>
  {% endif -%}

  {% if current_user.has_role('admin') or current_user.has_role('editor') -%}
  <li><a href="{{ url_for('admin.admin_or_editor') }}">Admin or Editor</a></li>
  {% endif -%}

    {%- if current_user.is_authenticated() -%}
      <li><a href="{{ url_for('frontend.generateurl') }}" style="color:white">Search</a></li>
      <li><a href="{{ url_for('frontend.members') }}" style="color:white"> My Collections</a></li>

        <li class="dropdown"><a href="#" class="dropdown " data-toggle="dropdown" style="color:white">Welcome, {{ current_user.username }}  <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for_security('change_password') }}"><i class="glyphicon glyphicon-cog"></i> Change Password</a></li>
                            <li><a href="#"><i class="glyphicon glyphicon-envelope"></i> Contact</a></li>
                            <li class="divider"></li>
                            <li><a href="{{ url_for_security('logout') }}" ><i class="glyphicon glyphicon-off"></i> Logout</a></li>
                        </ul>

                    </li>

    {%- else -%}
      {% if security.registerable %}
          <li><a href="{{ url_for('frontend.generateurldemo') }}" style="color:white">Demo</a></li>
           <li><a href="{{ url_for_security('register') }}" style="color:white">Register</a></li>
          {#<li><a href="{{ url_for('pricing') }}">Pricing & Plans</a></li>#}
      {% endif %}
      <li>
          <a href="{{ url_for_security('login') }}" style="color:white">Login</a>
      </li>

    {%- endif -%}
</ul>

flask_application/templates/security/change_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}

{% block title %}
Change Password
{% endblock %}

{% block content %}
<div class="login-container well">
<legend>Change password</legend>
<form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
  {{ change_password_form.hidden_tag() }}
  {{ render_field_with_errors(change_password_form.password) }}
  {{ render_field_with_errors(change_password_form.new_password) }}
  {{ render_field_with_errors(change_password_form.new_password_confirm) }}
  {{ render_field(change_password_form.submit) }}
</form>
</div>
{% endblock %}

flask_application/templates/security/forgot_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}

{% block title %}
Reset Password
{% endblock %}

{% block content %}
<div class="login-container well">
<legend>Send password reset instructions</legend>
<form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
  {{ forgot_password_form.hidden_tag() }}
  {{ render_field_with_errors(forgot_password_form.email) }}
  {{ render_field(forgot_password_form.submit, class_="btn-info btn") }}
</form>
</div>

{% endblock %}

flask_application/templates/security/index.html
{% extends "bootstrap/layouts/base_navbar_responsive.html" %}

{% block title %}
The Search Collective
{% endblock %}

{% block content %}
{{ content }}
{% endblock %}

flask_application/templates/security/login_user.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}


{% block title %}
Login
{% endblock %}

{% block content %}
<div class="login-container well">
<legend>Please Sign In</legend>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit, class_="btn-info btn") }}
</form>
<a href ="/auth/reset">Forget your password?</a>
</div>
{% endblock %}

flask_application/templates/security/register_user.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}

{% block title %}
Register
{% endblock %}

{% block content %}
<div class="login-container well">
<legend>Sign Up for The Search Collective!</legend>

<form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
  {{ register_user_form.hidden_tag() }}
{{ render_field_with_errors(register_user_form.username) }}</li>
 {{ render_field_with_errors(register_user_form.email) }}</li>
  {{ render_field_with_errors(register_user_form.password) }}
  {% if register_user_form.password_confirm %}
    {{ render_field_with_errors(register_user_form.password_confirm) }}
  {% endif %}
  {{ render_field(register_user_form.submit, class_="btn-info btn") }}
  {% if request.args.get('level') == 'medium' %}

  <p>Charge Button Here.</p>
  {% endif %}

</form>
</div>



{% endblock %}

flask_application/templates/security/reset_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}

{% block title %}
Reset Password
{% endblock %}

{% block content %}
<div class="login-container well">
<legend>Reset password</legend>
<form action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form">
  {{ reset_password_form.hidden_tag() }}
  {{ render_field_with_errors(reset_password_form.password) }}
  {{ render_field_with_errors(reset_password_form.password_confirm) }}
  {{ render_field(reset_password_form.submit, class_="btn") }}
</form>
</div>
{% endblock %}

flask_application/templates/security/send_confirmation.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}

{% block title %}
Resend confirmation
{% endblock %}

{% block content %}
<h1>Resend confirmation instructions</h1>
<form action="{{ url_for_security('send_confirmation') }}" method="POST" name="send_confirmation_form">
  {{ send_confirmation_form.hidden_tag() }}
  {{ render_field_with_errors(send_confirmation_form.email) }}
  {{ render_field(send_confirmation_form.submit, class_="btn") }}
</form>
{% include "security/_menu.html" %}
{% endblock %}

flask_application/templates/security/send_login.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% extends "security/index.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<h1>Login</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="send_login_form">
  {{ send_login_form.hidden_tag() }}
  {{ render_field_with_errors(send_login_form.email) }}
  {{ render_field(send_login_form.submit, class_="btn") }}
</form>
{% endblock %}